name: "Build thunderStorm"

on:
  push:
    branchs:
      - production

jobs:
  job-macos-1:
    name: "Build the macOS / AMD64 version of thunderStorm"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: "Remove Rust documentation"
        run: rustup component remove rust-docs
        continue-on-error: true
      - name: "Update Rust to the latest stable version"
        run: rustup update stable
      - name: Build release version
        run: cargo build --release
      - name: "Brag #1"
        run: find ./target -name "ths"
      - uses: actions/upload-artifact@v3
        with:
          name: thunderStorm-macos-amd64
          path: ./target/release/ths
          retention-days: 6

  job-linux-1:
    name: "Build the Linux / AMD64 version of thunderStorm"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Install GCC"
        run: |
          sudo apt update
          sudo apt install -y build-essential
          gcc --version
      - name: "Add support for MUSL"
        run: |
          sudo apt update
          sudo apt install -y musl-tools
          rustup target add $(uname -m)-unknown-linux-musl
      - name: "Remove Rust documentation"
        run: rustup component remove rust-docs
        continue-on-error: true
      - name: "Update Rust to the latest stable version"
        run: rustup update stable
      - name: Build release version
        run: cargo build --target $(uname -m)-unknown-linux-musl --release
      - name: "Brag #1"
        run: find ./target -name "ths"
      - uses: actions/upload-artifact@v3
        with:
          name: thunderStorm-linux-amd64
          path: ./target/x86_64-unknown-linux-musl/release/ths
          retention-days: 6

  job-windows-1:
    name: "Build the Windows / AMD64 version of thunderStorm"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: "Remove Rust documentation"
        run: rustup component remove rust-docs
        continue-on-error: true
      - name: "Update Rust to the latest stable version"
        run: rustup update stable
      - name: Build release version
        run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: thunderStorm-windows-amd64
          path: ./target/release/ths.exe
          retention-days: 6

  job-publish:
    name: "Publish an update"
    runs-on: ubuntu-latest
    needs:
      - job-linux-1
      - job-macos-1
      - job-windows-1
    steps:
      - name: "Download the Linux version"
        uses: actions/download-artifact@v3
        with:
          name: thunderStorm-linux-amd64
          path: ./release/linux/amd64
      - name: "Download the macOS version"
        uses: actions/download-artifact@v3
        with:
          name: thunderStorm-macos-amd64
          path: ./release/macos/amd64
      - name: "Download the Windows version"
        uses: actions/download-artifact@v3
        with:
          name: thunderStorm-windows-amd64
          path: ./release/windows/amd64
      - name: "Create a staging area"
        run: mkdir stage
      - name: "Rename the artifacts to include the operating system and architecture."
        run: |
          mv ./release/linux/amd64/ths ./stage/thunderStorm.linux.amd64
          mv ./release/macos/amd64/ths ./stage/thunderStorm.macos.amd64
          mv ./release/windows/amd64/ths.exe ./stage/thunderStorm.windows.amd64
      - name: "Brag #1"
        run: find ./release
      - name: "Brag #2"
        run: find ./stage
      - name: Release
        uses: softprops/action-gh-release@v1
        id: release
        with:
          tag_name: "current"
          files: |
            ./stage/*
